spring.application.name=phishing-detector-api
safebrowsing.api.key=AIzaSyBpH7QZvwyO60LxmVTPZ2ffBtcJJHuEtjk
server.port=${PORT:8080}
gemini.api.key=AQ.Ab8RN6L99BWZX4Y66ka6Y3OKi1NxtCeibc3vG-zRpPP5HZbcdg
